### ISSUE TITLE
Clean Code Fails to Open

### ISSUE THREAD

**Issue by theLaxerz** [letspython3x/Books#2]
The others work perfectly Clean Code...

**Comment by ssabzzz** [comment]
> The others work perfectly Clean Code...

Apparently it has a wrong extension. Save it and rename it to "Clean Code by Robert C Martin.pdf"

**Comment by theLaxerz** [comment]
Thanks.

**Comment by codams-org** [comment]
Clean Code book is updated with extension, now it opens successfully in browser.
[Clean Code](https://github.com/letspython3x/Books/blob/master/Clean%20Code%20by%20Robert%20C%20Martin.pdf)
